name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # adjust if your main branch is named differently

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_ENV: github  # this matches vite.config.js for setting base path

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build for GitHub Pages
        run: npm run build:github

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
